
export enum BM_NAME {
  EVASION = "Evasion",
  GIANT_RAT = "Giant Rat",
  BURN = "Brulûre",
  FIRE_BARRIER="Barrière de feu",
  WINGS="Ailes de la colère", 
  ROCK_SKIN = "Peau de roc",
  GUARD_REFLEX = "Bouclier réflexe",
  BLEED = "Saignement",
  SHIELD_EXPERT = "Bouclier expert",
  PROVOCATION = "Provocation",
  REGENERATION ="Charme de vitalité",
  ARCXOS = "Malédiciton d'Arcxos",
  DEEP_WOUND ="Blessure profonde",
  STRATEGIC_WAIT="Attente stratégique",
  BLEAK = "Putréfaction",
  SHATTERED="Désorienté",
  EXPOSED="Maudit", 
  WEAK="Faiblesse",
  WARD="Protection",
  WOLF_CRY="Appel de la meute",
  MM_POTION ="Potion de magie",
  STR_POTION="Potion de force",
  FATIGUE_MM="Mentalement fatigué",
  FATIGUE_STR="Physiquement fatigué",
  TROLL_REGEN="Régénération",
  TROLL_STR="Furie",
  ETHEREAL="Ethérée",
  SLOWNESS="Lenteur",
  GUARD_REFLEX_INFINITE="Bouclier réflexe",
  DAMAGE_CURSE = "Malédiction Drash'ar",
  
}


export enum BM_ID {
  EVASION = 1,
  GIANT_RAT = 3,
  WOLF_CRY = 4,
  BURN = 5,
  TROLL_FURY = 6,
  ROCK_SKIN = 7,
  GUARD_REFLEX = 8,
  BLEED = 9,
  DEEP_WOUND=10,
  SHIELD_EXPERT = 11,
  PROVOCATION = 12,
  SPIKE = 13,
  WINGS = 14,
  FIRE_BARRIER = 15,
  REGENERATION = 16,
  ARCXOS = 17,
  MM_POTION=18,
  STR_POTION=19,
  FATIGUE_MM=20,
  FATIGUE_STR=21,
  TROLL_STR=22,
  TROLL_REGEN=23,

  STRATEGIC_WAIT=25,
  BLEAK=26,
  SHATTERED=27,
  EXPOSED=28, 
  WEAK=29,
  ETHEREAL=30,
  WARD=31, 
  SLOWNESS=32,
  GUARD_REFLEX_INFINITE=33,
  SHORT_LIVED_ETHEREAL=34,
  DAMAGE_CURSE=35,
  LIFE_STEAL=36,
  GNOLL_POTION=37,
} 