import type { EquipmentType } from "../../../shared/types/equipmentView.js";
import  type {BasicEquipment } from "../types/basicEquipment.js";
import { BASIC_EQUIPMENT_ID } from "./constants.js";

export const BasicEquipments:BasicEquipment[] = [
{
    id:BASIC_EQUIPMENT_ID.HP_POTION,
  name: "Potion de vie",
  type: "potion",
  image: 1,
  width: 1,
  height: 1,
  price:24,
  text:"Restaure 5 à 8 pv",
  bonus: {},
},
{
    id:BASIC_EQUIPMENT_ID.STR_POTION,
  name: "Potion de force",
  type: "potion",
  image: 2,
  width: 1,
  height: 1,
  price:35,
  text:"+1 point de force",
   bonus: {},
},
{
    id:BASIC_EQUIPMENT_ID.MM_POTION,
  name: "Potion de mana",
  type: "potion",
  image: 3,
  width: 1,
  height: 1,
  price:35,
  text:"+1 point de MM",
   bonus: {},
},

{
    id:BASIC_EQUIPMENT_ID.REGEN_POTION,
  name: "Potion de regen",
  type: "potion",
  image: 3,
  width: 1,
  height: 1,
  price:35,
  text:"+4 points de regen",
   bonus: {},
},

{
    id:BASIC_EQUIPMENT_ID.ARMOR_POTION,
  name: "Potion d'armure",
  type: "potion",
  image: 3,
  width: 1,
  height: 1,
  price:35,
  text:"+3 points d'armure",
   bonus: {},
},

{
    id:BASIC_EQUIPMENT_ID.SHIELD_POTION,
  name: "Potion de bouclier",
  type: "potion",
  image: 3,
  width: 1,
  height: 1,
  price:35,
  text:"+15 point de bouclier",
   bonus: {},
},
{
    id:BASIC_EQUIPMENT_ID.RAT_TAIL,
  name: "Queue de rat",
  type: "ingredient",
  image: 1,
  width: 1,
  height: 1,
  price:8,
  text:"",
  bonus: {hp:1, strength:1},
},
{
  id:BASIC_EQUIPMENT_ID.TOAD_TONGUE,
  name: "Langue de crapaud",
  type: "ingredient",
  image: 2,
  width: 1,
  height: 1,
  price:8,
  text:"",
  bonus: {hp:1, magicSkill:1},
},
{
  id:BASIC_EQUIPMENT_ID.BAT_FANG,
  name: "Croc de chauve-souris",
  type: "ingredient",
  image: 3,
  width: 1,
  height: 1,
  price:8,
  text:"",
  bonus: {strength:1, magicSkill:1},
},
{
    id:BASIC_EQUIPMENT_ID.TROLL_BLOOD,
  name: "Sang de troll",
  type: "ingredient",
  image: 4,
  width: 1,
  height: 1,
  price:24,
  text:"",
  bonus: {regen:3, armor:2},
},
{
   id:BASIC_EQUIPMENT_ID.ETHEREAL_DUST,
  name: "Poussière d'éthérée",
  type: "ingredient",
  image: 5,
  width: 1,
  height: 1,
  price:32,
  text:"",
  bonus: {magicSkill:3, shield:3},
},
{
   id:BASIC_EQUIPMENT_ID.MUSHROOM,
  name: "Champignon ",
  type: "ingredient",
  image: 7,
  width: 1,
  height: 1,
  price:16,
  text:"",
  bonus: {shield:1, armor:2},
},
{
   id:BASIC_EQUIPMENT_ID.BONE_MARROW,
  name: "Moelle osseuse",
  type: "ingredient",
  image: 10,
  width: 1,
  height: 1,
  price:24,
  text:"",
  bonus: {regen:3, hp:2},
},
{
   id:BASIC_EQUIPMENT_ID.ECTOPLASM,
  name: "Ectoplasme",
  type: "ingredient",
  image: 7,
  width: 1,
  height: 1,
  price:24,
  text:"",
  bonus: {armor:3, strength:2},
},
{
   id:BASIC_EQUIPMENT_ID.EYE,
  name: "Oeil de goule",
  type: "ingredient",
  image: 9,
  width: 1,
  height: 1,
  price:20,
  text:"",
  bonus: {hp:3, shield:1 },
},
{
   id:BASIC_EQUIPMENT_ID.ROOT,
  name: "Racine de grisal",
  type: "ingredient",
  image: 6,
  width: 1,
  height: 1,
  price:24,
  text:"",
  bonus: {strength:3, regen:2},
},
    {
        id:BASIC_EQUIPMENT_ID.BASE_SWORD,
          name: "Sabre torsadé",
       
        type:  "sword",
        image:  2,
        width: 2,
        height: 3,
        price:150,
        text:"Dégât +1",
        bonus: {damage:1},
    },

  {
        id:BASIC_EQUIPMENT_ID.MEDIUM_SWORD,
        name: "Petite Hache",
        type:  "sword",
        image:  1,
        width: 2,
        height: 3,
        price:380,
        text:"Dégât +2",
        bonus: {damage:2},
  },

 {      id:BASIC_EQUIPMENT_ID.BASE_STAFF,
        name: "Bâton de mage",
        type:  "sword",
        image:  3,
        width: 2,
        height: 3,
        price:240,
        text:"MM +1",
        bonus: {magicSkill:1},
 },
 
 {      id:BASIC_EQUIPMENT_ID.MEDIUM_STAFF,
        name: "Bâton de mage",
        type:  "sword",
        image:  3,
        width: 2,
        height: 3,
        price:520,
        text:"MM +2",
        bonus: {magicSkill:2},
 },


  {     
         id:BASIC_EQUIPMENT_ID.BASE_ARMOR,
        name: "Armure de cuir",
        type:  "armor",
        image:  1,
        width: 2,
        height: 3,
        price:150,
        text:"Armure +1",
        bonus: {armor:1},
  },

 {
        id:BASIC_EQUIPMENT_ID.MEDIUM_ARMOR,
        name: "Armure de cuir renforcé",
        type:  "armor",
        image:  2,
        width: 2,
        height:3,
        price:380,
        text:"Armure +2",
        bonus: {armor:2},
 },
 
 {      id:BASIC_EQUIPMENT_ID.BASE_TOGE,
        name: "Robe de mage supérieur",
        type:  "armor",
        image:  6,
        width: 2,
        height:3,
        price:380,
        text:"MM +1",
        bonus: {magicSkill:1},
 },

 {      id:BASIC_EQUIPMENT_ID.MEDIUM_TOGE,
        name: "Robe de mage supérieur",
        type:  "armor",
        image:  6,
        width: 2,
        height:3,
        price:520,
        text:"MM +2",
        bonus: {magicSkill:2},
 },

   {    id:BASIC_EQUIPMENT_ID.BASE_SHIELD,
        name: "Bouclier rond",
        type:  "shield",
        image:  1,
        width: 2,
        height:3,
        price:120,
        text:"Bouclier +1",
        bonus: {shield_bonus:1},
    },
 
     {      
        id:BASIC_EQUIPMENT_ID.MEDIUM_SHIELD,
        name: "Bouclier rond",
        type:  "shield",
        image:  1,
        width: 2,
        height:3,
        price:300,
        text:"Bouclier +2",
        bonus: {shield_bonus:2},
    },
 
 {      id:BASIC_EQUIPMENT_ID.BASE_HELM,
        name: "Capuche de cuir ",
        type:  "helm",
        image:  2,
        width: 2,
        height:2,
        price:150,
        text:"Armure +1",
        bonus: {armor:1},
    },

 {      id:BASIC_EQUIPMENT_ID.MEDIUM_HELM,
        name: "Casque plein ",
        type:  "helm",
        image:  2,
        width: 2,
        height:2,
        price:380,
        text:"Armure +2",
        bonus: {armor:2},
    },
    {    
        id:BASIC_EQUIPMENT_ID.SIGIS_SWORD,
        name: "Sabre torsadé de robutesse",
        type:  "sword",
        image:  4,
        width: 2,
        height:3,
        price:920,
        text:"Cons +1 - Dégât +2",
        bonus: {damage:2, constitution:1},
    },
     {    
        id:BASIC_EQUIPMENT_ID.GUNTHAR_AXE,
        name: "Grande Hahce de bataille",
        type:  "sword",
        image:  5,
        width: 2,
        height:3,
        price:720,
        text:"Dégât +3",
        bonus: {damage:3},
    },
    {    
        id:BASIC_EQUIPMENT_ID.ARCANE_TOGA_1,
        name: "Toge du dernier arcaniste",
        type:  "armor",
        image:  8,
        width: 2,
        height:3,
        price:1800,
        text:"Cons +1 - Magie +2",
        bonus: {magicSkill:2, alteration:1},
    },
    {    
        id:BASIC_EQUIPMENT_ID.ARCANE_TOGA_2,
        name: "Toge du dernier arcaniste",
        type:  "armor",
        image:  8,
        width: 2,
        height:3,
        price:1800,
        text:"Magie +1, destruction +3",
        bonus: {magicSkill:1, destruction:3},
    },
    {    
        id:BASIC_EQUIPMENT_ID.ARCANE_TOGA_3,
        name: "Toge du dernier arcaniste",
        type:  "armor",
        image:  8,
        width: 2,
        height:3,
        price:1800,
        text:"Magie +1 - guerison:3",
        bonus: {magicSkill:1, guerison:3},
    },
    {    
        id:BASIC_EQUIPMENT_ID.ARCANE_TOGA_4,
        name: "Toge du dernier arcaniste",
        type:  "armor",
        image:  8,
        width: 2,
        height:3,
        price:1800,
        text:"Armure +3 - Magie +2",
        bonus: {magicSkill:1, protection:3},
    },

];


export const getBasicEquipment = (
  id: number
): BasicEquipment => {
  const equip = BasicEquipments.find(
    (equip) => equip.id === id
  );

  if (!equip) {
    throw new Error(
      `BasicEquipment introuvable : ${id}`
    );
  }

  return equip;
};