
import { Bm } from "../classes/Bm.js";
import type { BasicBm} from "../types/basicBm.js";
import { BM_ID, BM_NAME } from "../../../shared/utils/bmConstant.js";


export const basicBms:BasicBm[] = [ 
  {
    id:BM_ID.EVASION,
    name: BM_NAME.EVASION,
    image: 5,
    life:-1,
    removable:true,
    enchantment:false,
    display:"normal",
    mainStat:"evasion",
    type:"value_cumulative",
    bonus: {evasion:1}
  },
  {
    id:BM_ID.BLEED,
    name: BM_NAME.BLEED,
    image:14,
    life:-1,
     removable:true,
      enchantment:false,
    display:"normal",
    mainStat:"regen",
    type:"value_cumulative",
    bonus: {regen:-1},
  },
  {
    id:BM_ID.BURN,
    name: BM_NAME.BURN,
    image:22,
    life:3,
    removable:true,
     enchantment:false,
    display:"both",
    mainStat:"regen",
    type:"both_cumulative",
    bonus: {regen:-1},
  },
  {
    id:BM_ID.WINGS,
    name: BM_NAME.WINGS,
    image:6,
    life:2,
    removable:true,
    enchantment:true,
    display:"both",
    mainStat:"strength",
    type:"replaced",
    bonus: {strength:1},
  },
  {
    id:BM_ID.GIANT_RAT,
    name: "Rage",
     enchantment:false,
    image:3,
    life:1,
     removable:true,
    display:"none",
    mainStat:"damage",
    type:"replaced",
    bonus: {damage:1},
  },
  {
    id:BM_ID.FIRE_BARRIER,
    name: BM_NAME.FIRE_BARRIER,
    image:11,
    life:3,
     removable:true,
      enchantment:true,
    display:"both",
    mainStat:"spike",
    type:"life_cumulative",
    bonus: {spike:1},
  },
   {
    id:BM_ID.REGENERATION,
    name: BM_NAME.REGENERATION,
    image:17,
    life:3,
    removable:true,
     enchantment:true,
    display:"both",
    mainStat:"regen",
    type:"life_cumulative",
    bonus: {regen:1},
  },
  {
    id:BM_ID.ROCK_SKIN,
    name: BM_NAME.ROCK_SKIN,
    image:15,
    life:3,
    removable:true,
     enchantment:true,
    display:"both",
    mainStat:"armor",
    type:"replaced",
    bonus: {armor:1},
  },
  {
    id:BM_ID.GUARD_REFLEX,
    name: BM_NAME.GUARD_REFLEX,
    image:8,
    life:3,
    removable:true,
     enchantment:true,
    display:"both",
    mainStat:"reflex",
    type:"replaced",
    bonus: {reflex:1},
  },
   {
    id:BM_ID.WOLF_CRY,
    name: BM_NAME.WOLF_CRY,
    image:12,
    life:-1,
    removable:true,
     enchantment:false,
    display:"normal",
    mainStat:"damage",
    type:"value_cumulative",
    bonus: {damage:1},
  },
   {
    id:BM_ID.MM_POTION,
    name: BM_NAME.MM_POTION,
    image:42,
    life:5,
    removable:true,
     enchantment:true,
    display:"both",
    mainStat:"magicSkill",
    type:"both_cumulative",
    bonus: {magicSkill:1},
  },
   {
    id:BM_ID.STR_POTION,
    name: BM_NAME.STR_POTION,
    image:43,
    life:5,
    removable:true,
     enchantment:true,
    display:"both",
    mainStat:"strength",
    type:"both_cumulative",
    bonus: {strength:1},
  },
   {
    id:BM_ID.FATIGUE_MM,
    name: BM_NAME.FATIGUE_MM,
    image:39,
    life:-1,
    removable:false,
     enchantment:false,
    display:"normal",
    mainStat:"magicSkill",
    type:"value_cumulative",
    bonus: {magicSkill:-1},
  },
   {
    id:BM_ID.FATIGUE_STR,
    name: BM_NAME.FATIGUE_STR,
    image:41,
    life:-1,
    removable:false,
     enchantment:false,
    display:"normal",
    mainStat:"strength",
    type:"value_cumulative",
    bonus: {strength:-1},
  },
   {
    id:BM_ID.TROLL_REGEN,
    name: BM_NAME.TROLL_REGEN,
    image:17,
    life:-1,
    removable:true,
    display:"normal",
     enchantment:false,
    mainStat:"regen",
    type:"value_cumulative",
    bonus: {regen:1},
  },
   {
    id:BM_ID.TROLL_STR,
    name: BM_NAME.TROLL_STR,
    image:41,
    life:-1,
    removable:false,
    display:"normal",
     enchantment:false,
    mainStat:"damage",
    type:"value_cumulative",
    bonus: {damage:1},
  },
   {
    id:BM_ID.ARCXOS,
     name: BM_NAME.ARCXOS,
    image:41,
    life:3,
    removable:true,
     enchantment:false,
    display:"both",
    mainStat:"damage",
    type:"life_cumulative",
    bonus: {damage:-1},
  },
   {
    id:BM_ID.SHIELD_EXPERT,
    name: BM_NAME.SHIELD_EXPERT,
    image:28,
    life:-1,
    removable:true,
     enchantment:false,
    display:"empty",
    mainStat:"shield_expert",
    type:"replaced",
    bonus: {shield_expert:1},
  },
   {
    id:BM_ID.PROVOCATION,
     name: BM_NAME.PROVOCATION,
    image:19,
    life:-1,
    removable:true,
     enchantment:false,
    display:"empty",
    mainStat:"provocation",
    type:"replaced",
    bonus: {provocation:1},
  },
   {
    id:BM_ID.STRATEGIC_WAIT,
    name: BM_NAME.STRATEGIC_WAIT,
    image:20,
    life:1,
    removable:true,
     enchantment:false,
    display:"life",
    mainStat:"ap",
    type:"replaced",
    bonus: {ap: 1},
  },
   {
    id:BM_ID.BLEAK,
    name: BM_NAME.BLEAK,
    image:4,
    life:-1,
    removable:true,
     enchantment:false,
    display:"normal",
    mainStat:"regen",
    type:"value_cumulative",
    bonus: {regen: -1},
  },
  {
    id:BM_ID.SHATTERED,
    name: BM_NAME.SHATTERED,
    image:21,
    life:3,
    removable:true,
     enchantment:false,
    display:"both",
    mainStat:"shield_bonus",
    type:"replaced",
    bonus: {shield_bonus: -1},
  },
   {
    id:BM_ID.WEAK,
    name: BM_NAME.WEAK,
    image:7,
    life:3,
    removable:true,
     enchantment:false,
    display:"both",
    mainStat:"damage",
    type:"replaced",
    bonus: {damage: -1},
  },
   {
    id:BM_ID.EXPOSED,
    name: BM_NAME.EXPOSED,
    image:4,
    life:3,
    removable:true,
     enchantment:false,
    display:"life",
    mainStat:"exposed",
    type:"replaced",
    bonus: {exposed: -1},
  },
   {
    id:BM_ID.ETHEREAL,
     name: BM_NAME.ETHEREAL,
    image:2,
    life:-1,
    removable:false,
     enchantment:false,
    display:"empty",
    mainStat:"ethereal",
    type:"replaced",
    bonus: {ethereal: 1},
  },
    {
    id:BM_ID.WARD,
    name: BM_NAME.WARD,
    image:3,
    life:-1,
    removable:true,
    display:"normal",
     enchantment:false,
    mainStat:"ward",
    type:"value_cumulative",
    bonus: {ward: 1},
  },
   {
    id:BM_ID.DEEP_WOUND,
    name: BM_NAME.DEEP_WOUND,
    image:41,
    life:3,
    removable:true,
     enchantment:false,
    display:"both",
    mainStat:"damage",
    type:"value_cumulative",
    bonus: {damage: -1},
  },
  {
    id:BM_ID.SLOWNESS,
    name: BM_NAME.SLOWNESS,
    image:9,
    life:4,
    removable:true,
     enchantment:false,
    display:"life",
    mainStat:"ap",
    type:"replaced",
    bonus: {ap: -1},
  },
  {
    id:BM_ID.GUARD_REFLEX_INFINITE,
    name: BM_NAME.GUARD_REFLEX_INFINITE,
    image:8,
    life:-1,
    removable:true,
     enchantment:false,
    display:"normal",
    mainStat:"reflex",
    type:"replaced",
    bonus: {reflex: 1},
  },
  {
    id:BM_ID.SHORT_LIVED_ETHEREAL,
    name: BM_NAME.ETHEREAL,
    image:2,
    life:1,
    removable:false,
     enchantment:false,
    display:"life",
    mainStat:"ethereal",
    type:"replaced",
    bonus: {ethereal: 1},
  },
  {
    id:BM_ID.DAMAGE_CURSE,
    name: BM_NAME.DAMAGE_CURSE,
    image:23,
    life:1,
    removable:false,
     enchantment:false,
    display:"empty",
    mainStat:"exposed",
    type:"replaced",
    bonus: {},
  },
   {
    id:BM_ID.LIFE_STEAL,
    name: "Vol de vie",
    image:23,
    life:-1,
    removable:false,
    enchantment:false,
    display:"normal",
    mainStat:"lifeSteal",
    type:"replaced",
    bonus: {lifeSteal:1},
  },
    {
    id:BM_ID.GNOLL_POTION,
    name: "Potion de force",
    image:43,
    life:2,
    removable:false,
    enchantment:false,
    display:"both",
    mainStat:"damage",
    type:"replaced",
    bonus: {damage:1},
  },
  
  



];




export const getBasicBm = (id:number):BasicBm => {
    const bm = basicBms.find((bm) => bm.id === id);
   
    
    
  if (!bm) {
    throw new Error(
      `BasicBm introuvable : ${id}`
    );
  }

  return bm;
}
