
import type { BasicNpc, TargetSelectMode } from "../types/basicNpc.js";
import { BM_ID, BM_NAME } from "../../../shared/utils/bmConstant.js";

import { NPC_ID } from "./constants.js";



export const basicNpcs:BasicNpc[] = [ 
  {
      id: 1,
      image : 1,
      name:"Rat Géant",
      size:1,
      favoriteTarget : {
        feature: "damage",
        mode : "max",
      },
      level_start:1,
      hp_start:33,
      armor_start:0,
      shield_start:0,
      damage_start:3,
      magicSkill_start:1,
      power_start: 0,
      bm_start:[],
      upgradeRate: {
          hp : 50,
          armor: 0,
          damage:50,
          magicSkill:0,
          power:0,
          bm: 0, 
        },
      bms: [],
   },
  


  {
      id: 2,
      image : 2,
      name:"Crapaud Géant",
      size:1,
      favoriteTarget : {
        feature: "maxhp",
        mode : "max",
      },
      level_start:1,
      hp_start:54,
      armor_start:2,
      damage_start:5,
      shield_start:2,
      magicSkill_start:0,
      power_start: 7,
      bm_start:[],
      upgradeRate: {
          hp : 50,
          armor: 30,
          damage:0,
          magicSkill:0,
          power:20,
          bm: 0, 
        },
      bms: [],
   },



  {
      id: 3,
      image : 3,
      name:"Chauve-souris Géante",
      size:1,
      favoriteTarget : {
        feature: "maxhp",
        mode : "min",
      },
      level_start:1,
      hp_start:17,
      armor_start:0,
      damage_start:2,
      magicSkill_start:2,
      shield_start:0,
      power_start: 1,
       bm_start:[1],
      upgradeRate: {
          hp : 10,
          armor: 0,
          damage:20,
          magicSkill:0,
          power:20,
          bm: 50, 
        },
      bms: [BM_ID.EVASION],
   },

   {
      id: 4,
      image :4,
      name:"Loup",
      size:1,
      favoriteTarget : {
        feature: "currhp",
        mode : "max",
      },
      level_start:2,
      hp_start:45,
      armor_start:2,
      damage_start:6,
      shield_start:2,
      magicSkill_start:0,
      power_start: 1,
      bm_start:[],
      upgradeRate: {
          hp : 30,
          armor: 0,
          damage:60,
          magicSkill:0,
          power:10,
          bm: 0, 
        },
      bms: [],
   },
   {
      id: 5,
      image :5,
      name:"Kobold",
      size:1,
      favoriteTarget : {
        feature: "damage",
        mode : "max",
      },
      level_start:2,
      hp_start:37,
      armor_start:0,
      damage_start:7,
      magicSkill_start:0,
      shield_start:0,
      power_start: 3,
      bm_start:[],
      upgradeRate: {
          hp : 30,
          armor: 0,
          damage:50,
          magicSkill:0,
          power:20,
          bm: 0, 
        },
      bms: [],
   },
    {
      id: 6,
      image :6,
      name:"Troll",
      size:4,
      favoriteTarget : {
        feature: "magicSkill",
        mode : "max",
      },
      level_start:7,
      hp_start:170,
      armor_start:5,
      shield_start:5,
      damage_start:9,
      magicSkill_start:2,
      power_start: 12,
      bm_start:[],
      upgradeRate: {
          hp : 30,
          armor: 0,
          damage:60,
          magicSkill:0,
          power:10,
          bm: 0, 
        },
      bms: [],
   },
    {
      id: 7,
      image :7,
      name:"Ogre à 2 têtes",
      size:3,
      favoriteTarget : {
        feature: "strength",
        mode : "min",
      },
      level_start:10,
      hp_start:131,
      armor_start:11,
      damage_start:17,
      magicSkill_start:3,
      power_start: 27,
      shield_start:11,
       bm_start:[1],
      upgradeRate: {
          hp : 30,
          armor: 30,
          damage:40,
          magicSkill:0,
          power:0,
          bm: 0, 
        },
      bms: [BM_ID.SHIELD_EXPERT, BM_ID.PROVOCATION],
   },
    {
      id: 8,
      image :9,
      name:"Brigand",
      size:1,
      favoriteTarget : {
        feature: "currhp",
        mode : "max",
      },
      level_start:3,
      shield_start:0,
      hp_start:17,
      armor_start:0,
      damage_start:7,
      magicSkill_start:0,
      power_start: 0,
       bm_start:[],
      upgradeRate: {
          hp : 100,
          armor: 0,
          damage:0,
          magicSkill:0,
          power:0,
          bm: 0, 
        },
      bms: []
   },
    {
      id: NPC_ID.GOULE,
      image :10,
      name:"Goule",
      size:1,
      favoriteTarget : {
        feature: "currhp",
        mode : "max",
      },
      level_start:5,
      hp_start:47,
      armor_start:0,
      damage_start:11,
      shield_start:0,
      magicSkill_start:8,
      power_start: 3,
      bm_start:[8],
      upgradeRate: {
          hp : 20,
          armor: 0,
          damage:40,
          magicSkill:30,
          power:10,
          bm: 0, 
        },
      bms: [BM_ID.GUARD_REFLEX_INFINITE]
   },
   {
      id: NPC_ID.SOUL,
      image :11,
      name:"Ame en peine",
      size:3,
      favoriteTarget : {
        feature: "constitution",
        mode : "max",
      },
      level_start:10,
      hp_start:47,
      armor_start:0,
      shield_start:0,
      damage_start:1,
      magicSkill_start:18,
      power_start: 3,
      bm_start:[1],
      

      upgradeRate: {
          hp : 30,
          armor: 0,
          damage:0,
          magicSkill:50,
          power:20,
          bm: 0, 
        },
       //  bms:[],
       bms: [BM_ID.ETHEREAL]
   },
   {
      id: NPC_ID.ZOMBIE,
      image :12,
      name:"Zombie",
      size:1,
      favoriteTarget : {
        feature: "magicSkill",
        mode : "min",
      },
      level_start:7,
      hp_start:72,
      armor_start:0,
      damage_start:12,
      shield_start:0,
      magicSkill_start:5,
      power_start: 3,
      bm_start:[],
      upgradeRate: {
          hp : 77,
          armor: 0,
          damage:0,
          magicSkill:50,
          power:20,
          bm: 0, 
        },
        bms:[],
      //bms: [BM_ID.ETHEREAL]
   },
    {
      id: NPC_ID.NECROMANCIEN,
      image :13,
      name:"Mernguil",
      size:1,
      favoriteTarget : {
        feature: "maxhp",
        mode : "max",
      },
      level_start:10,
      hp_start:52,
      armor_start:2,
      shield_start:2,
      damage_start:9,
      magicSkill_start:6,
      power_start: 4,
      bm_start:[3],
      upgradeRate: {
          hp : 30,
          armor: 0,
          damage:0,
          magicSkill:50,
          power:20,
          bm: 0, 
        },
        bms:[BM_ID.GUARD_REFLEX_INFINITE],
     
   },
     {
      id: NPC_ID.MANTIS,
      image :16,
      name:"Mante religieuse géante",
      size:1,
      favoriteTarget : {
        feature: "magicSkill",
        mode : "max",
      },
      level_start:3,
      hp_start:48,
      armor_start:0,
      shield_start:0,
      damage_start:8,
      magicSkill_start:6,
      power_start: 3,
      bm_start:[],
      upgradeRate: {
          hp : 20,
          armor: 0,
          damage:70,
          magicSkill:0,
          power:10,
          bm: 0, 
        },
        bms:[],
     
   },
    {
      id: NPC_ID.BLACK_ANGEL,
      image :14,
      name:"Ange noir",
      size:3,
      favoriteTarget : {
        feature: "magicSkill",
        mode : "max",
      },
      level_start:10,
      hp_start:100,
      armor_start:0,
      shield_start:30,
      damage_start:6,
      magicSkill_start:10,
      power_start: 4,
      bm_start:[],
      upgradeRate: {
          hp : 0,
          armor: 0,
          damage:100,
          magicSkill:0,
          power: 0,
          bm: 0, 
        },
        bms:[],
     
   },
   
    {
      id: NPC_ID.WHITE_ANGEL,
      image :15,
      name:"Ange blanc",
      size:3,
      favoriteTarget : {
        feature: "magicSkill",
        mode : "max",
      },
      level_start:10,
      hp_start:100,
      armor_start:0,
      damage_start:10,
      shield_start:0,
      magicSkill_start:10,
      power_start: 4,
      bm_start:[1],
      upgradeRate: {
          hp : 0,
          armor: 0,
          damage:0,
          magicSkill:100,
          power:0,
          bm: 0, 
        },
        bms:[BM_ID.SHORT_LIVED_ETHEREAL],
     
   },
     {
      id: NPC_ID.GNOLL,
      image :20,
      name:"Gnool",
      size:3,
      favoriteTarget : {
        feature: "damage",
        mode : "max",
      },
      level_start:10,
      hp_start:100,
      armor_start:3,
      damage_start:6,
      shield_start:3,
      magicSkill_start:2,
      power_start: 1,
      bm_start:[3,1],
      upgradeRate: {
          hp : 30,
          armor: 30,
          damage:30,
          magicSkill:10,
          power:0,
          bm: 0, 
        },
        bms:[BM_ID.GUARD_REFLEX_INFINITE, BM_ID.LIFE_STEAL],
     
   },
   

]

export function getTargetSelectMode(basicNpcId:number):TargetSelectMode {
   const npc = basicNpcs.find((npc) => npc.id === basicNpcId);
   if(!npc) {
    throw(new Error(
      `BasicNpc introuvable : ${basicNpcId}`
    ))
   }
   return npc.favoriteTarget;
}