
import { Bm } from "../classes/Bm.js";
import type { BasicBm} from "../types/basicBm.js";
import { BM_ID } from "./constants.js";


export const basicBms:BasicBm[] = [ 
  {
    id:BM_ID.EVASION,
    name: "Evasion",
    image: 5,
    life:-1,
    removable:true,
    display:"normal",
    mainStat:"evasion",
    type:"value_cumulative",
    bonus: {evasion:1}
  },
  {
    id:BM_ID.FATIGUE,
    name: "Fatigué",
    image:3,
    life:-1,
    removable:false,
    display:"normal",
    mainStat:"strength",
    type:"value_cumulative",
    bonus: {strength:-1},
  },
  {
    id:BM_ID.BLEED,
    name: "Saignement",
    image:14,
    life:-1,
     removable:true,
    display:"normal",
    mainStat:"regen",
    type:"value_cumulative",
    bonus: {regen:-1},
  },
  {
  id:BM_ID.BURN,
    name: "Brulûre",
    image:22,
    life:3,
     removable:true,
    display:"both",
    mainStat:"regen",
    type:"both_cumulative",
    bonus: {regen:-1},
  },
  {
    id:BM_ID.WINGS,
    name: "Ailes de colère",
    image:6,
    life:2,
    removable:true,
    display:"both",
    mainStat:"strength",
    type:"replaced",
    bonus: {strength:1},
  },
  {
    id:BM_ID.GIANT_RAT,
    name: "Rage",
    image:3,
    life:1,
     removable:true,
    display:"none",
    mainStat:"damage",
    type:"replaced",
    bonus: {damage:1},
  },
  {
    id:BM_ID.FIRE_BARRIER,
    name: "Barrière de feu",
    image:11,
    life:3,
     removable:true,
    display:"both",
    mainStat:"spike",
    type:"life_cumulative",
    bonus: {spike:1},
  },
   {
    id:BM_ID.REGENERATION,
    name: "Régénération",
    image:17,
    life:3,
     removable:true,
    display:"both",
    mainStat:"regen",
    type:"life_cumulative",
    bonus: {regen:1},
  },
  {
    id:BM_ID.ROCK_SKIN,
    name: "Peau de roc",
    image:15,
    life:3,
    removable:true,
    display:"both",
    mainStat:"armor",
    type:"replaced",
    bonus: {armor:1},
  },
  {
    id:BM_ID.GUARD_REFLEX,
    name: "Bouclier reflexe",
    image:8,
    life:3,
     removable:true,
    display:"both",
    mainStat:"reflex",
    type:"replaced",
    bonus: {reflex:1},
  },
   {
    id:BM_ID.WOLF_CRY,
    name: "Appel de meute",
    image:12,
    life:-1,
    removable:true,
    display:"normal",
    mainStat:"damage",
    type:"value_cumulative",
    bonus: {damage:1},
  },
   {
    id:BM_ID.MM_POTION,
    name: "Potion de mana",
    image:42,
    life:5,
    removable:true,
    display:"both",
    mainStat:"magicSkill",
    type:"both_cumulative",
    bonus: {magicSkill:1},
  },
   {
    id:BM_ID.STR_POTION,
    name: "Potion de force",
    image:43,
    life:5,
    removable:true,
    display:"both",
    mainStat:"strength",
    type:"both_cumulative",
    bonus: {strength:1},
  },
   {
    id:BM_ID.FATIGUE_MM,
    name: "Fatigué",
    image:39,
    life:-1,
    removable:true,
    display:"normal",
    mainStat:"magicSkill",
    type:"value_cumulative",
    bonus: {magicSkill:-1},
  },
   {
    id:BM_ID.FATIGUE_STR,
    name: "Potion de force",
    image:41,
    life:-1,
    removable:false,
    display:"normal",
    mainStat:"strength",
    type:"value_cumulative",
    bonus: {strength:-1},
  },
   {
    id:BM_ID.TROLL_REGEN,
    name: "Regen",
    image:17,
    life:-1,
    removable:true,
    display:"normal",
    mainStat:"regen",
    type:"value_cumulative",
    bonus: {regen:1},
  },
   {
    id:BM_ID.TROLL_STR,
    name: "Force",
    image:41,
    life:-1,
    removable:false,
    display:"normal",
    mainStat:"damage",
    type:"value_cumulative",
    bonus: {damage:1},
  },
   {
    id:BM_ID.ARCXOS,
    name: "Arcxos",
    image:41,
    life:3,
    removable:true,
    display:"both",
    mainStat:"damage",
    type:"life_cumulative",
    bonus: {damage:-1},
  },
   {
    id:BM_ID.SHIELD_EXPERT,
    name: "Bouclier expert",
    image:28,
    life:-1,
    removable:true,
    display:"empty",
    mainStat:"shield_expert",
    type:"replaced",
    bonus: {shield_expert:1},
  },
   {
    id:BM_ID.PROVOCATION,
    name: "Provocation",
    image:19,
    life:-1,
    removable:true,
    display:"empty",
    mainStat:"provocation",
    type:"replaced",
    bonus: {provocation:1},
  },
   {
    id:BM_ID.DEEP_WOUND,
    name: "Blessure pronfonde",
    image:20,
    life:3,
    removable:true,
    display:"both",
    mainStat:"damage",
    type:"replaced",
    bonus: {damage:-1},
  },

];




export const getBasicBm = (id:number):BasicBm => {
    const bm = basicBms.find((bm) => bm.id === id);
   
    
    
  if (!bm) {
    throw new Error(
      `BasicBm introuvable : ${id}`
    );
  }

  return bm;
}
