
import {NPC_ACTION_ID } from "../../../shared/utils/npcActionConstant.js"
export enum NB_MAX {
  ABILITY_MAX = 10,
  NB_QUEST = 6,

}

export enum COMPANION_ID {
 GLADYS=2,
 SIGUIS=3,
 GUNTHAR=4,
}
export enum FIGHT_VALUE {
  BASIC_DAMAGE = 5,
  BASIC_SHIELD = 3,
  BASIC_ACTION_AP = 1,
  NEW_TURN_AP = 3,

  //GUERRIER
  BRUTAL_BLOW_BASE=11,
  BRUTAL_BLOW_MULT=3,

  TWIRL_BASE = 6,
  TWIRL_MULT= 3,

  DEEP_THRUST_BASE = 6,
  DEEP_THRUST_MULT = 2,
  DEEP_THRUST_BLEED_BASE = 1,
  DEEP_THRUST_BLEED_MULT = 2,

  SHATTERING_ATTACK_BASE = 1,
  SHATTERING_ATTACK_MULT = 2,
  
  //ASSASSIN
  PARRY_SHIELD = 1,
  PARRY_DAMAGE = 3,
  PARRY_MULT=1,
  
  TREACHEROUS_ATTACK_BASE = 6,
  TREACHEROUS_ATTACK_WOUND_BASE =1,
  TREACHEROUS_ATTACK_WOUND_MULT =1,

  MULTIPLE_ATTACK_DAMAGE = 2,
  MULTIPLE_ATTACK_ITERATION = 2,

  //GUERISON
  TEARS_BASE = 7,
  TEARS_MULT = 3,

  REGENERATION_BASE = 2,
  REGENERATION_MULT = 1,

  //PROTECTION 
  ROCK_BASE = 2,
  ROCK_MULT= 1, 

  ATHLAN_SHIELD_BASE = 1,
  ATHLAN_SHIELD_MULT = 2,

  ATHLAN_ARMOR_BASE = 2,
  ATHLAN_ARMOR_MULT = 2,

  //GUARDIEN
  AUTOREGENERATION_BASE = 7,
  AUTOREGENERATION_MULT = 3,

  GUARD_BASE = 7,
  GUARD_MULT = 3, 
  
  GUARD_REFLEX_BASE = 1,
  GUARD_REFLEX_MULT = 2,

  
  CHARGE_BASE = 14,
  CHARGE_MULT = 6,

  //DESTRUCTION
  FIREBALL_BASE = 6,
  FIREBALL_MULT = 1,
  FIREBALL_BURN_BASE = 2,
  FIREBALL_BURN_MULT = 1,

  FIRE_BARRIER_BASE = 1,
  FIRE_BARRIER_MULT = 2,

  BLAZING_FIRE_BASE = 6,
  BLAZING_FIRE_MULT= 3,

  //ALTERATION
  WINGS_BASE = 1,
  WINGS_MULT = 1,
  WINGS_LIFE = 3,

  ARCXOS_BASE = 1,
  ARCXOS_MULT = 2,




  
}




export enum ABILITY_NAME {

  //WARRIOR
  BRUTAL_BLOW = "Dégâts accrus",
  DEEP_THRUST ="Coup tranchant",
  TWIRL ="Tourbillon",
  SHATTERING_ATTACK="Attaque dévastatrice",

  
  //GUARDIAN
  ROCK_SKIN = "Peau de roc",
  AUTOREGENERATION = "Autorégénération",
  GUARD_REFLEX = "Bouclier reflexe",
  CHARGE = "Charge",
  GUARD = "Posture défensive",

  //ASSASSIN
  MULTIPLE_ATTACK = "Rafale",
  PARRY = "Botte d'estoc",
  TREACHEROUS_ATTACK="coup traitre",

  //GUERISION
  LIFE_TEARS = "Larme de vie",
  REGENERATION = "Charme de vitalité",
  HOLY_RAIN ="Pluie guérissante",
  HEALING_SUN = "Soleil de guérison",
  CURE = "Souffle d'Athlan",
  
  //PROTECTION
  ATHLAN_SHIELD = "Bouclier d'Athlan",
  ATHLAN_ARMOR = "Armure d'Athlan",
  WARD = "Protection divine",
  // procure shield_expert pour 1+2*MM tour
  


  //ALTERATION
  WINGS="Ailes de colère",
  ARCXOS = "Malédiction d'Arcxos",
  BLEAK = "Sang de Lave",
  //Exposed --> perd 1+2*MM pv de plus chaque fois qu'il est touché pour le tour en cours


  
  //DESTRUCTION
  FIRE_BARRIER = "Barrière de feu",
  FIREBALL ="Boule de feu",
  VOID_RAY="Rayon du vide",
  BLAZING_FIRE="Brasier",

  //TALENT
  PROVOCATION = "Provocation",
  FIRST_AID = "Premier soin", 
  LIGHT_TOUCH = "Touché de lumière", 
  STRATEGIC_WAIT = "Attente stratégique", 
  DAMAGE_CURSE = "Malédiction de Drash'ar",
  ENCHANTMENT_EXPERT="Souffle d'Athlan",
  BUCKLER_HIT="Coup de bouclier",
  EVASION="Illusion",
  KNIVE_THROWING="Lancer de couteau",

}




export enum NPC_ID {
  GIANT_RAT = 1,
  GIANT_TOAD = 2,
  GIANT_BAT = 3,
  WOLF = 4,
  KOBOLD = 5,
  TROLL = 6,
  OGRE = 7,
  BRIGAND = 8,
  GOULE = 9,
  SOUL = 10,
  ZOMBIE=11,
  NECROMANCIEN=12,
  MANTIS=13,
  BLACK_ANGEL=14,
  WHITE_ANGEL=15,
  GNOLL=16,
  
  
}

export enum SCHOOL_NAME {
  WARRIOR = "Guerrier",
  GUARDIAN = "Gardien",
  ASSASSIN = "Assassin",
  DESTRUCTION = "Destruction",
  GUERISON ="Guérison",
  ALTERATION ="Altération",
  PROTECTION ="Protection"
 
  
}


export const NPC_ACTION_ID_NEED_INTENT_CHANGE = [
  NPC_ACTION_ID.RAT_ATTACK, 
  NPC_ACTION_ID.BURN_ATTACK,
  NPC_ACTION_ID.TWIRL,
  NPC_ACTION_ID.PIERCING_ATTACK,
  NPC_ACTION_ID.MULTIPLE_ATTACK,
  NPC_ACTION_ID.VAMPIRE_ATTACK,
  NPC_ACTION_ID.BLEAK_ATTACK,
  NPC_ACTION_ID.WOLF_ATTACK,
  NPC_ACTION_ID.TROLL_ATTACK,
  NPC_ACTION_ID.TOAD_ATTACK,
]


export const NPC_ACTION_ID_CHANGE_UNDER_PROVOCATION = [
  NPC_ACTION_ID.RAT_ATTACK, 
  NPC_ACTION_ID.BURN_ATTACK,
  NPC_ACTION_ID.PIERCING_ATTACK,
  NPC_ACTION_ID.MULTIPLE_ATTACK,
  NPC_ACTION_ID.VAMPIRE_ATTACK,
  NPC_ACTION_ID.BLEAK_ATTACK,
  NPC_ACTION_ID.WOLF_ATTACK,
  NPC_ACTION_ID.TROLL_ATTACK,
  NPC_ACTION_ID.TOAD_ATTACK,
  NPC_ACTION_ID.PIERCING_ATTACK,

  
]



export enum BASIC_EQUIPMENT_ID {
  HP_POTION= 1,
  STR_POTION= 2,
  MM_POTION= 3,
  RAT_TAIL= 4,
  TOAD_TONGUE= 5,
  BAT_FANG=6,
  BASE_SWORD=7,
  BASE_STAFF=9,
  BASE_ARMOR=10,
  BASE_HELM=14,
  BASE_SHIELD=15,
  BASE_TOGE=16, 
  
  MEDIUM_SWORD=11,
  MEDIUM_STAFF=12,
  MEDIUM_ARMOR=13,
  MEDIUM_HELM=17,
  MEDIUM_SHIELD=18,
  MEDIUM_TOGE=19,

  TROLL_BLOOD=20,
  SIGIS_SWORD=21,
  ETHEREAL_DUST=22,

  ARCANE_TOGA_1=23,
  ARCANE_TOGA_2=24,
  ARCANE_TOGA_3=25,
  ARCANE_TOGA_4=26,

  ROOT = 27,
  EYE = 28,
  ECTOPLASM=29,
  BONE_MARROW=30,
  MUSHROOM=31,

  ARMOR_POTION=32,
  SHIELD_POTION=33,
  REGEN_POTION=34,

  GUNTHAR_AXE = 35,



  
  
} 